import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/utils/Header";
import Footer from "@/components/utils/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Global Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} leading-normal tracking-normal text-white `} >
       <div>
         <Header/>
         {children}
         <Footer/>
        </div>
        </body>
    </html>
  );
}
